# Generated by Django 2.2.6 on 2021-08-14 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(blank=True, upload_to='post_pictures/', validators=[main.models.validate_file_size], verbose_name='')),
                ('content', models.TextField(default='')),
                ('num_like', models.IntegerField(default=0)),
                ('likes', jsonfield.fields.JSONField(default={}, null=True)),
                ('comments', jsonfield.fields.JSONField(default={}, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
